### ISSUE TITLE
One use "qualification"

### ISSUE THREAD

**Issue by ernesto418** [Infineon/remote-attestation-optiga-tpm#1]
Hello,
 I found a problem related the the "qualification" (challenge).
It is not deleted in the "Attest" process in coreService.java therefore until the Raspberry-pi executes "4_atelic.sh" again, it cans relaunch "7_attest.sh" and be accepted.

I think it could be easily solved setting the qualification to null by the server (coreServer.java) in:

`public Response<String> restAttest(@RequestBody Attest attest) {`

when it is successfully imported:

` 

            if (tpm.import_qualification(user.getQualification()) != true) {
                //We can delete the qualification to avoid futures replay attacks
                user.setQualification(null);
                userRepository.save(user);
                return new Response<String>(Response.STATUS_ERROR, "bad qualification format");
            }`

P.D.: I found useful this repository

**Comment by wxleong** [comment]
This is a valid concern but the qualification should be nullify outside the IF scope. It is now fixed in 43fa2b2.

**Comment by wxleong** [comment]
This is a valid concern but the qualification should be nullify outside the IF scope. It is now fixed in 1fd385a.

**Comment by ernesto418** [comment]
Perfect.
